### ISSUE TITLE
Tooltip 

### ISSUE THREAD

**Issue by Ccald** [AusDVA/myservice-prototype#1065]
Need to investigate a best-practice tooltip. 

Current tooltip not positioning properly with multi-line question.

**Comment by AllySummers** [comment]
could you show us an example of the multi line tooltip not working properly? just so i understand what you mean :)

**Comment by Ccald** [comment]
https://myservice-disco.herokuapp.com/auth/claim/il/claim1

**Comment by AllySummers** [comment]
@mattmcinerney and i discovered this is an issue with where the tooltip element lays in the HTML, not a CSS issue.

Tooltips should be placed within the label or legend element, like so:

```html
<label class="label">
    This is the label text
    <div class="tooltip">With a tooltip within the label</div>
</label>```

In this case, it goes like this:
```html
<label class="label">
    This is the label text
</label>
<div class="tooltip">With a tooltip outside the label</div>```

If this is done, it fixes the issue with positioning and possibly also makes it slightly more accessible for people with screen readers (because in this case they know the tooltip relates to the element).

We need to update the styleguide to reflect this and also update the form partials that are doing the tooltip placement.
